# Generated by Django 5.1.7 on 2025-03-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-created"]},
        ),
    ]
