# Generated by Django 5.1.7 on 2025-03-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_record_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="display_color",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="pdf_file",
        ),
    ]
