# Generated by Django 5.1.7 on 2025-03-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_record_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
