# Generated by Django 5.1.7 on 2025-03-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_item_delete_itemcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="main.record",
            ),
        ),
    ]
